  model_type: batchtopk
  device: ${device}
  dict_size: 128  # 768/4
  input_shape: 768
  top_k: 32
  top_k_aux: 512
  n_batches_to_dead: 20
  l1_coeff: 0.0
  aux_penalty: 0.03125  # 1/32
  bandwidth: 0.001
  group_sizes: null
  input_unit_norm: true
  dtype: float32
  lr: 5e-4
  betas:
    - 0.9
    - 0.99
  eps: 1e-08
  weight_decay: 0.0
  final_sae_path: ${paths.final_sae_path}